### ISSUE TITLE
Log file issue

### ISSUE THREAD

**Issue by ErikHougaard** [in3otd/spiki#2]
I am trying to run this tool on an Ubuntu machine, but I get this error:

Traceback (most recent call last):
  File "spiki.py", line 121, in runSimulation
    self.simulate()
  File "spiki.py", line 181, in simulate
    sf.run()
  File "/home/erik/fasthenry-3.0wr/bin/dos.py", line 308, in run
    cmd, shell=False, universal_newlines=True, stdout=flog)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

It's probably a noob thing but I hope someone can give me a hint. Thanks.

Erik

**Comment by in3otd** [comment]
I think that `spiki` is trying to run `fasthenry` but does not find it; is it in the path, can you run it from the command line?
